describe('Cart fitur', ()=>{
    beforeEach(()=>{
        cy.visit('https://www.saucedemo.com/')
        cy.get('#user-name').type('standard_user')
        cy.get('#password').type('secret_sauce')
        cy.get('#login-button').click()
        cy.url().should('include', '/inventory')
    })
    it('Remove product from cart', ()=>{
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#item_4_title_link > div').should('be.visible')
        cy.get('#remove-sauce-labs-backpack').click()
    })
    it('Checkout product', ()=>{
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#checkout').click()
        cy.get('#first-name').type('indah')
        cy.get('#last-name').type('students')
        cy.get('#postal-code').type('20211')
        cy.get('#continue').click()
        cy.contains('Checkout: Overview').should('be.visible')
        cy.get('#finish').click()
        cy.contains('Thank you for your order!').should('be.visible')
    })
        it('Checkout product with blank username', ()=>{
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#checkout').click()
        cy.get('#last-name').type('students')
        cy.get('#postal-code').type('20211')
        cy.get('#continue').click()
        cy.contains('Error: First Name is required').should('be.visible')
    })
        it('Checkout product with blank last name', ()=>{
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#checkout').click()
        cy.get('#first-name').type('indah')
        cy.get('#postal-code').type('20211')
        cy.get('#continue').click()
        cy.contains('Error: Last Name is required').should('be.visible')
    })
        it('Checkout product with blank last name', ()=>{
        cy.get('#add-to-cart-sauce-labs-backpack').click()
        cy.get('#shopping_cart_container > a').click()
        cy.get('#checkout').click()
        cy.get('#first-name').type('indah')
        cy.get('#last-name').type('students')
        cy.get('#continue').click()
        cy.contains('Error: Postal Code is required').should('be.visible')
    })
})